import { AlertTriangle, Banknote, Cpu, CheckCircle2, Wrench, Share2, Calendar, Hash, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter, SheetClose } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { ScanRecord } from "@/hooks/use-scan-history";

interface HistoryDetailSheetProps {
  record: ScanRecord | null;
  onClose: () => void;
}

export function HistoryDetailSheet({ record, onClose }: HistoryDetailSheetProps) {
  const getPriceEstimate = (text: string) => {
    const lower = (text || "").toLowerCase();
    if (lower.includes("ic") || lower.includes("cpu") || lower.includes("emmc") || lower.includes("short")) {
      return "Rp 250.000 - Rp 500.000";
    }
    if (lower.includes("konektor") || lower.includes("lcd") || lower.includes("fleksibel") || lower.includes("usb")) {
      return "Rp 75.000 - Rp 150.000";
    }
    return "Rp 50.000 - Rp 100.000";
  };

  const handleShare = () => {
    if (!record) return;
    const estimate = getPriceEstimate(record.diagnosis);
    const text = `*TECHYST REPORT [${record.id.slice(0, 4)}]*\n\n📅 Date: ${new Date(record.date).toLocaleDateString("id-ID")}\n⚠️ Issue: ${record.diagnosis}\n💰 Est. Cost: ${estimate}\n\n_Generated by AI Vision_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
  };

  return (
    <Sheet open={!!record} onOpenChange={onClose}>
      <SheetContent className="overflow-y-auto sm:max-w-xl w-full flex flex-col h-full bg-slate-950 border-l border-white/10 p-0 shadow-2xl">
        {record && (
          <>
            <div className="sticky top-0 z-20 bg-slate-950/80 backdrop-blur-md border-b border-white/5 p-6 pb-4">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <div className="h-8 w-8 rounded bg-primary/10 flex items-center justify-center border border-primary/20">
                    <Hash className="h-4 w-4 text-primary" />
                  </div>
                  <div>
                    <h2 className="text-sm font-mono text-muted-foreground tracking-widest">DIAGNOSIS_LOG</h2>
                    <p className="text-xs font-mono text-primary">ID: {record.id.slice(0, 8).toUpperCase()}</p>
                  </div>
                </div>
                <SheetClose className="rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-secondary">
                  <X className="h-6 w-6 text-muted-foreground hover:text-white transition-colors" />
                  <span className="sr-only">Close</span>
                </SheetClose>
              </div>

              <h3 className="text-xl font-bold font-sans tracking-tight text-foreground leading-tight">{record.diagnosis || "Unidentified Issue"}</h3>
              <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground font-mono">
                <Calendar className="h-3 w-3" />
                {new Date(record.date).toLocaleString("id-ID", { dateStyle: "full", timeStyle: "short" })}
              </div>
            </div>

            <div className="flex-1 p-6 space-y-6">
              <div className="rounded-xl overflow-hidden border border-white/10 bg-black relative group shadow-lg">
                <div className="absolute inset-0 bg-grid-pattern opacity-30 pointer-events-none" />
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={record.imagePreview} alt="Full Scan" className="w-full h-auto max-h-[350px] object-contain relative z-10 bg-black/50" />
                <div className="absolute bottom-3 left-3 z-20">
                  <Badge variant="secondary" className="bg-black/60 backdrop-blur border border-white/20 text-[10px] font-mono">
                    VISUAL_EVIDENCE
                  </Badge>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 rounded-xl border border-blue-500/20 bg-blue-500/5 hover:bg-blue-500/10 transition-colors">
                  <h4 className="text-[10px] font-bold text-blue-400 font-mono flex items-center gap-2 uppercase tracking-wider mb-2">
                    <Banknote className="h-3 w-3" /> Est. Cost
                  </h4>
                  <p className="text-lg font-bold font-sans text-foreground">{getPriceEstimate(record.diagnosis)}</p>
                </div>
                <div className="p-4 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors">
                  <h4 className="text-[10px] font-bold text-muted-foreground font-mono flex items-center gap-2 uppercase tracking-wider mb-2">
                    <Cpu className="h-3 w-3" /> Hardware
                  </h4>
                  <div className="flex flex-wrap gap-1.5">
                    {(record.components || []).length > 0 ? (
                      record.components.map((comp, idx) => (
                        <span key={idx} className="text-[10px] px-2 py-0.5 rounded border border-white/10 bg-black/30 text-slate-300">
                          {comp}
                        </span>
                      ))
                    ) : (
                      <span className="text-xs text-muted-foreground italic">N/A</span>
                    )}
                  </div>
                </div>
              </div>

              <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-5 relative overflow-hidden">
                <div className="absolute top-0 right-0 p-3 opacity-10">
                  <AlertTriangle className="h-16 w-16 text-amber-500" />
                </div>
                <h4 className="text-xs font-bold text-amber-500 font-mono uppercase tracking-wider flex items-center gap-2 mb-3">
                  <CheckCircle2 className="h-4 w-4" /> AI Analysis Log
                </h4>
                <p className="text-sm text-slate-300 leading-relaxed font-sans relative z-10">{record.analysis || "No detailed analysis data recorded for this session."}</p>
              </div>

              <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 relative overflow-hidden">
                <div className="absolute top-0 right-0 p-3 opacity-10">
                  <Wrench className="h-16 w-16 text-green-500" />
                </div>
                <h4 className="text-xs font-bold text-green-500 font-mono uppercase tracking-wider flex items-center gap-2 mb-3">
                  <Wrench className="h-4 w-4" /> Repair Protocol
                </h4>
                <p className="text-sm text-slate-300 leading-relaxed font-sans relative z-10 border-l-2 border-green-500/30 pl-4">{record.recommendation || "No recommendation available. Consult manual inspection."}</p>
              </div>
            </div>

            <SheetFooter className="p-6 border-t border-white/5 bg-slate-950">
              <Button className="w-full bg-primary hover:bg-primary/90 text-primary-foreground font-bold h-12 shadow-[0_0_20px_rgba(6,182,212,0.2)]" onClick={handleShare}>
                <Share2 className="mr-2 h-4 w-4" />
                Export Report to WhatsApp
              </Button>
            </SheetFooter>
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}
